version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: something
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public'
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    command: ['sh', '-c', 'pnpm prisma migrate deploy && pnpm start']

volumes:
  pgdata:
